export interface ICreateContentRequest {
    contentTypeId: number;
    titr: string;
    lead: string;
    contentText: string;
    picFile: string;
    releaseTime: Date;
    label: string;
    favorite: boolean;
    visitNo: number;
    confirmed: boolean;
    telegram: boolean;
    telegramSent: boolean;
    files: string;
    sourceTitle: string;
    sourceLink: string;
    authorUserAccountId: number;
    likeNum: number;
    disLikeNum: number;
    insertDate: Date;
    lastUpdate: Date;
    videoFile: string;
    voiceFile: string;
    expireDate: Date;
    newsPaper: true,
    picAlt: string;
    keyword: string;
    title: string;
    adLocation: number;
    englishTitr: string;
    showLocation: number;
}